const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d");
const midiInput=document.getElementById("midi-input"),playBtn=document.getElementById("play-btn"),modeBtn=document.getElementById("mode-btn"),clearBtn=document.getElementById("clear-btn"),synthSelect=document.getElementById("synth-select"),bpmSlider=document.getElementById("bpm-slider"),bpmVal=document.getElementById("bpm-val"),trackListEl=document.getElementById("track-list"),addTrackBtn=document.getElementById("add-track-btn"),addDrumBtn=document.getElementById("add-drum-btn");
const MIN_NOTE=21,MAX_NOTE=108,TOTAL_NOTES=88;
const TRACK_COLORS=["#9fb0ff","#67d7b0","#f6c76f","#ef8fbd","#b493ff","#66c8df"];
const DRUM_LANES=[{midi:49,name:"Crash"},{midi:42,name:"Hi-Hat"},{midi:46,name:"Open HH"},{midi:38,name:"Snare"},{midi:37,name:"Side Stick"},{midi:36,name:"Kick"},{midi:35,name:"Kick 2"},{midi:45,name:"Low Tom"},{midi:47,name:"Mid Tom"},{midi:50,name:"High Tom"},{midi:51,name:"Ride"},{midi:39,name:"Clap"}];
let beatWidth=40,noteHeight=16,tracks=[],currentTrackIndex=0,isPlaying=false,currentBeat=0,playTimer=null,mode="scroll",bpm=120,scrollX=0,scrollY=0;
const activeTouches=new Map();let initialPinchDistance=null,initialBeatWidth=beatWidth,initialNoteHeight=noteHeight,initialScrollX=0,initialScrollY=0,singleStartTouch={x:0,y:0};

function createSynth(type){let C=Tone.Synth;if(type==="fm")C=Tone.FMSynth;if(type==="am")C=Tone.AMSynth;return new Tone.PolySynth(C,{maxPolyphony:32,options:{envelope:{attack:.005,decay:.09,sustain:.28,release:.18}}}).toDestination()}
function createDrumKit(){return{
kick:new Tone.MembraneSynth({pitchDecay:.02,octaves:5,envelope:{attack:.001,decay:.15,sustain:0,release:.04}}).toDestination(),
snare:new Tone.NoiseSynth({noise:{type:"white"},envelope:{attack:.001,decay:.1,sustain:0,release:.02}}).toDestination(),
hat:new Tone.MetalSynth({frequency:250,harmonicity:5.1,modulationIndex:32,resonance:2800,octaves:1.5,envelope:{attack:.001,decay:.045,release:.015}}).toDestination(),
tom:new Tone.MembraneSynth({pitchDecay:.02,octaves:3,envelope:{attack:.001,decay:.18,sustain:0,release:.04}}).toDestination(),
clap:new Tone.NoiseSynth({noise:{type:"pink"},envelope:{attack:.001,decay:.08,sustain:0,release:.02}}).toDestination(),
crash:new Tone.MetalSynth({frequency:250,harmonicity:5.1,modulationIndex:35,resonance:3000,octaves:1.8,envelope:{attack:.001,decay:.5,release:.1}}).toDestination(),
ride:new Tone.MetalSynth({frequency:330,harmonicity:5.1,modulationIndex:25,resonance:3200,octaves:1.2,envelope:{attack:.001,decay:.3,release:.06}}).toDestination()
}}
function disposeDrumKit(k){if(!k)return;Object.values(k).forEach(s=>{try{s.dispose()}catch(_){}})}
function triggerDrum(track,midi){const k=track.drumKit;if(!k)return;try{
if(midi===35||midi===36)k.kick.triggerAttackRelease("C1","16n");
else if(midi===37)k.snare.triggerAttackRelease("32n");
else if(midi===38||midi===40)k.snare.triggerAttackRelease("16n");
else if(midi===39)k.clap.triggerAttackRelease("16n");
else if(midi===42||midi===44||midi===46)k.hat.triggerAttackRelease("32n");
else if([45,47,48,50].includes(midi))k.tom.triggerAttackRelease("G2","16n");
else if(midi===49)k.crash.triggerAttackRelease("16n");
else if([51,53,59].includes(midi))k.ride.triggerAttackRelease("16n");
}catch(_){}}
function addTrack(name=null,synthType="synth",isDrum=false){const id=tracks.length,color=TRACK_COLORS[id%TRACK_COLORS.length],t={id,name:name||`Track ${id+1}`,color,synthType,isDrum,synth:isDrum?null:createSynth(synthType),drumKit:isDrum?createDrumKit():null,notes:[]};tracks.push(t);currentTrackIndex=tracks.length-1;updateTrackUI();render()}
function addDrumTrack(){addTrack(`Drums ${tracks.filter(t=>t.isDrum).length+1}`,"synth",true)}
function updateTrackUI(){trackListEl.innerHTML="";tracks.forEach((t,i)=>{const item=document.createElement("div");item.className=`track-item ${i===currentTrackIndex?"active":""}`;const b=document.createElement("span");b.className="track-color-badge";b.style.backgroundColor=t.isDrum?"#ef8fbd":t.color;b.style.color=t.isDrum?"#ef8fbd":t.color;const n=document.createElement("span");n.textContent=t.name+(t.isDrum?" 🥁":"");item.append(b,n);item.onclick=()=>{currentTrackIndex=i;if(!t.isDrum)synthSelect.value=t.synthType;updateTrackUI();render()};trackListEl.appendChild(item)})}
synthSelect.onchange=e=>{const t=tracks[currentTrackIndex];if(!t||t.isDrum)return;t.synth.dispose();t.synthType=e.target.value;t.synth=createSynth(t.synthType)}
addTrackBtn.onclick=()=>addTrack();addDrumBtn.onclick=()=>addDrumTrack();
bpmSlider.oninput=e=>{bpm=+e.target.value;bpmVal.textContent=bpm;if(isPlaying)restartTimer()};
function resizeCanvas(){const dpr=Math.max(1,devicePixelRatio||1),w=innerWidth,h=document.getElementById("editor-container").clientHeight;canvas.width=Math.max(1,Math.floor(w*dpr));canvas.height=Math.max(1,Math.floor(h*dpr));canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);scrollY=Math.min(scrollY,Math.max(0,TOTAL_NOTES*noteHeight-h));render()}addEventListener("resize",resizeCanvas,{passive:true});
modeBtn.onclick=()=>{if(mode==="scroll"){mode="edit";modeBtn.textContent="モード: 打ち込み";modeBtn.classList.remove("btn-amber");modeBtn.classList.add("btn-purple")}else{mode="scroll";modeBtn.textContent="モード: スクロール";modeBtn.classList.remove("btn-purple");modeBtn.classList.add("btn-amber")}};
midiInput.onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const buffer=await file.arrayBuffer(),m=new Midi(buffer);tracks.forEach(t=>{try{t.synth?.dispose()}catch(_){}disposeDrumKit(t.drumKit)});tracks=[];const fileBpm=Math.round(m.header.tempos[0]?.bpm||120);bpm=Math.max(40,Math.min(240,fileBpm));bpmSlider.value=bpm;bpmVal.textContent=bpm;m.tracks.forEach(tr=>{if(!tr.notes.length)return;const drum=tr.channel===9;addTrack(tr.name||`${drum?"Drums":"Track"} ${tracks.length+1}`,"synth",drum);const t=tracks.at(-1);tr.notes.forEach(n=>t.notes.push({note:n.midi,startBeat:n.time*(fileBpm/60),duration:Math.max(n.duration*(fileBpm/60),.25)}))});if(!tracks.length)addTrack();currentTrackIndex=0;updateTrackUI();stopPlayback();scrollX=0;scrollY=Math.max(0,TOTAL_NOTES*noteHeight-canvas.clientHeight*.66);render()}catch(err){console.error(err);alert("MIDIファイルを読み込めませんでした。")}finally{midiInput.value=""}};

function buildPlaybackEvents(){const events=new Map();for(const t of tracks)for(const n of t.notes){const step=Math.round(n.startBeat/.25)*.25;if(!events.has(step))events.set(step,[]);events.get(step).push({track:t,note:n})}return events}
function startPlayback(){isPlaying=true;playBtn.textContent="停止";playBtn.classList.remove("btn-green");playBtn.classList.add("btn-amber");restartTimer()}
function restartTimer(){if(playTimer)clearInterval(playTimer);const events=buildPlaybackEvents(),intervalMs=60/bpm/4*1000;playTimer=setInterval(()=>{const ev=events.get(Math.round(currentBeat/.25)*.25)||[];for(const e of ev){try{if(e.track.isDrum)triggerDrum(e.track,e.note.note);else e.track.synth.triggerAttackRelease(Tone.Frequency(e.note.note,"midi").toNote(),"8n")}catch(_){}}const x=currentBeat*beatWidth;if(x-scrollX>canvas.clientWidth*.78||x<scrollX)scrollX=Math.max(0,x-110);render();currentBeat+=.25},intervalMs)}
function stopPlayback(){isPlaying=false;playBtn.textContent="再生";playBtn.classList.remove("btn-amber");playBtn.classList.add("btn-green");if(playTimer)clearInterval(playTimer);playTimer=null;currentBeat=0;render()}
playBtn.onclick=async()=>{await Tone.start();isPlaying?stopPlayback():startPlayback()};
clearBtn.onclick=()=>{tracks.forEach(t=>t.notes=[]);stopPlayback();render()};

canvas.addEventListener("pointerdown",async e=>{await Tone.start();canvas.setPointerCapture(e.pointerId);activeTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activeTouches.size===1){singleStartTouch={x:e.clientX,y:e.clientY};initialScrollX=scrollX;initialScrollY=scrollY;if(mode==="edit"&&tracks[currentTrackIndex]){const t=tracks[currentTrackIndex],r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let midiNote;if(t.isDrum){const idx=Math.floor((y+scrollY)/noteHeight);midiNote=DRUM_LANES[Math.min(DRUM_LANES.length-1,Math.max(0,idx))]?.midi}else{const idx=TOTAL_NOTES-1-Math.floor((y+scrollY)/noteHeight);midiNote=MIN_NOTE+idx}const beat=(x+scrollX)/beatWidth,targetBeat=Math.floor(beat);if(midiNote!=null){const a=t.notes,i=a.findIndex(n=>n.note===midiNote&&Math.abs(n.startBeat-targetBeat)<.5);if(i>=0)a.splice(i,1);else{a.push({note:midiNote,startBeat:targetBeat,duration:1});try{t.isDrum?triggerDrum(t,midiNote):t.synth.triggerAttackRelease(Tone.Frequency(midiNote,"midi").toNote(),"8n")}catch(_){}}render()}}}if(activeTouches.size===2){const p=[...activeTouches.values()];initialPinchDistance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);initialBeatWidth=beatWidth;initialNoteHeight=noteHeight}});
canvas.addEventListener("pointermove",e=>{if(!activeTouches.has(e.pointerId))return;activeTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activeTouches.size===2&&initialPinchDistance){const p=[...activeTouches.values()],scale=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/initialPinchDistance;beatWidth=Math.max(10,Math.min(150,initialBeatWidth*scale));noteHeight=Math.max(6,Math.min(50,initialNoteHeight*scale));scrollY=Math.min(scrollY,Math.max(0,TOTAL_NOTES*noteHeight-canvas.clientHeight));render();return}if(activeTouches.size===1&&mode==="scroll"){scrollX=Math.max(0,initialScrollX-(e.clientX-singleStartTouch.x));scrollY=Math.max(0,Math.min(Math.max(0,TOTAL_NOTES*noteHeight-canvas.clientHeight),initialScrollY-(e.clientY-singleStartTouch.y)));render()}});
function end(e){activeTouches.delete(e.pointerId);if(activeTouches.size<2)initialPinchDistance=null}canvas.addEventListener("pointerup",end);canvas.addEventListener("pointercancel",end);

function roundRect(x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function noteName(m){const a=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];return a[m%12]+(Math.floor(m/12)-1)}
function render(){const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,"#0a0c13");bg.addColorStop(1,"#06080d");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
const drum=tracks[currentTrackIndex]?.isDrum;
if(drum){DRUM_LANES.forEach((d,i)=>{const y=i*noteHeight-scrollY;ctx.fillStyle=i%2?"rgba(255,255,255,.025)":"rgba(255,255,255,.012)";ctx.fillRect(0,y,w,noteHeight);ctx.strokeStyle="rgba(255,255,255,.07)";ctx.beginPath();ctx.moveTo(0,y+.5);ctx.lineTo(w,y+.5);ctx.stroke();if(y>0&&y<h){ctx.fillStyle="rgba(220,225,240,.3)";ctx.font="600 9px system-ui";ctx.fillText(d.name,6,y+noteHeight-4)}})}else{for(let i=0;i<TOTAL_NOTES;i++){const m=MIN_NOTE+(TOTAL_NOTES-1-i),y=i*noteHeight-scrollY;if(y+noteHeight<0||y>h)continue;const black=[1,3,6,8,10].includes(m%12);ctx.fillStyle=black?"rgba(255,255,255,.018)":"rgba(145,157,190,.028)";ctx.fillRect(0,y,w,noteHeight);ctx.strokeStyle="rgba(255,255,255,.055)";ctx.beginPath();ctx.moveTo(0,y+.5);ctx.lineTo(w,y+.5);ctx.stroke()}}
const sb=Math.floor(scrollX/beatWidth),eb=sb+Math.ceil(w/beatWidth)+2;for(let b=sb;b<eb;b++){const x=b*beatWidth-scrollX;ctx.strokeStyle=b%4===0?"rgba(210,220,255,.2)":b%2===0?"rgba(185,195,230,.075)":"rgba(255,255,255,.035)";ctx.beginPath();ctx.moveTo(x+.5,0);ctx.lineTo(x+.5,h);ctx.stroke()}
tracks.forEach((t,ti)=>{const active=ti===currentTrackIndex;t.notes.forEach(n=>{const idx=t.isDrum?DRUM_LANES.findIndex(d=>d.midi===n.note):TOTAL_NOTES-1-(n.note-MIN_NOTE);if(idx<0)return;const x=n.startBeat*beatWidth-scrollX,y=idx*noteHeight-scrollY,w2=Math.max(n.duration*beatWidth,4),hh=Math.max(noteHeight-2,3);if(x+w2<=0||x>=w||y+hh<=0||y>=h)return;ctx.globalAlpha=active?.92:.2;ctx.fillStyle=t.isDrum?"#ef8fbd":t.color;roundRect(x+1,y+1,Math.max(w2-2,2),hh,2.5);ctx.fill();if(active){ctx.strokeStyle="rgba(255,255,255,.6)";ctx.stroke()}})});
ctx.globalAlpha=1;if(isPlaying){const x=currentBeat*beatWidth-scrollX;ctx.strokeStyle="rgba(255,105,120,.9)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();ctx.lineWidth=1}}
addTrack();requestAnimationFrame(resizeCanvas);
